services:
  mysql:
    image: mysql:8.0
    container_name: mysqlcont
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adaline
      MYSQL_DATABASE: catalogdb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:6
    container_name: mongocont
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    environment:
      REDIS_URL: "redis://redis-cache:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  postgres:
    image: postgres:latest
    container_name: postgrescont
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: adaline
      POSTGRES_DB: ordersdb
      PGDATA: /var/lib/postgresql/data/pgdata   # <-- IMPORTANT
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-U", "root"]
      interval: 5s
      timeout: 5s
      retries: 10

  catalog:
    build: ./backend/catalog-service
    container_name: catalog-service
    ports:
      - "3001:3001"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: adaline
      MYSQL_DATABASE: catalogdb
    depends_on:
      mysql:
        condition: service_healthy

  cart:
    build: ./backend/cart-service
    container_name: cart-service
    ports:
      - "3002:3002"
    environment:
      MONGO_URI: mongodb://mongocont:27017/cartdb
      REDIS_HOST: redis-cache
    depends_on:
      - mongo
      - redis

  orders:
    build: ./backend/orders-service
    container_name: orders-service
    ports:
      - "3003:3003"
    environment:
      PGHOST: postgrescont
      PGUSER: root
      PGPASSWORD: adaline
      PGDATABASE: ordersdb
      MONGO_URI: mongodb://mongocont:27017/cartdb
      REDIS_URL: "redis://redis-cache:6379"
      PGPORT: "5432"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend/ui
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - catalog
      - cart
      - orders 

volumes:
  mysql_data:
  mongo_data:
  pg_data: