apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS catalogdb;
    USE catalogdb;
    CREATE TABLE IF NOT EXISTS products (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(255),
      price INT
    );

    INSERT IGNORE INTO products (id, name, price) 
    VALUES 
    (1,'Laptop',70000),
    (2,'Phone',30000),
    (3,'Insta360',50000),
    (4,'Headphones',5000);
