apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: shop.local
    http:
      paths:
      - path: /products
        pathType: Prefix
        backend:
          service:
            name: catalogh
            port:
              number: 3001

      - path: /cart
        pathType: Prefix
        backend:
          service:
            name: carth
            port:
              number: 3002

      - path: /orders
        pathType: Prefix
        backend:
          service:
            name: ordersh
            port:
              number: 3003
      - path: /checkout
        pathType: Prefix
        backend:
          service:
            name: ordersh
            port:
              number: 3003

      - path: /
        pathType: Prefix
        backend:
          service:
            name: uih
            port:
              number: 80
