name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Catalog Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/catalog:latest ./catalog
          docker push ${{ secrets.DOCKER_USERNAME }}/catalog:latest

      - name: Build & Push Cart Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cart:latest ./cart
          docker push ${{ secrets.DOCKER_USERNAME }}/cart:latest

      - name: Build & Push Orders Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/orders:latest ./orders
          docker push ${{ secrets.DOCKER_USERNAME }}/orders:latest

      - name: Build & Push UI Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ui:latest ./ui
          docker push ${{ secrets.DOCKER_USERNAME }}/ui:latest
