name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Catalog Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/catalogcicd:latest ./backend/catalog-service
          docker push ${{ secrets.DOCKER_USERNAME }}/catalogcicd:latest

      - name: Build & Push Cart Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cartcicd:latest ./backend/cart-service
          docker push ${{ secrets.DOCKER_USERNAME }}/cartcicd:latest

      - name: Build & Push Orders Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/orderscicd:latest ./backend/orders-service
          docker push ${{ secrets.DOCKER_USERNAME }}/orderscicd:latest

      - name: Build & Push UI Image
        run: |
          docker build -f frontend/ui/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/uicicd:latest ./frontend/ui
          docker push ${{ secrets.DOCKER_USERNAME }}/uicicd:latest
