name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Catalog Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/catalogcicd:latest ./backend/catalog-service
          docker push ${{ secrets.DOCKER_USERNAME }}/catalogcicd:latest

      - name: Build & Push Cart Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cartcicd:latest ./backend/cart-service
          docker push ${{ secrets.DOCKER_USERNAME }}/cartcicd:latest

      - name: Build & Push Orders Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/orderscicd:latest ./backend/orders-service
          docker push ${{ secrets.DOCKER_USERNAME }}/orderscicd:latest

      - name: Build & Push UI Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/uicicd:latest ./frontend/ui
          docker push ${{ secrets.DOCKER_USERNAME }}/uicicd:latest
      
      # 8Ô∏è‚É£ Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v4

      # 9Ô∏è‚É£ Lint Helm charts (YOUR CHARTS)
      - name: Helm lint
        run: |
          helm lint k8-charts/catalogh
          helm lint k8-charts/carth
          helm lint k8-charts/ordersh
          helm lint k8-charts/uih

      # üîü Update image tag in Helm values (FOR FRONTEND UI)
      - name: Update Helm image tag (UI)
        run: |
          sed -i "s/tag:.*/tag: \"${{ github.sha }}\"/" k8-charts/uih/values.yaml

      # (Optional) If you also want to update backend images:
      - name: Update Helm image tags (All services)
        run: |
          sed -i "s/tag:.*/tag: \"${{ github.sha }}\"/" k8-charts/catalogh/values.yaml
          sed -i "s/tag:.*/tag: \"${{ github.sha }}\"/" k8-charts/carth/values.yaml
          sed -i "s/tag:.*/tag: \"${{ github.sha }}\"/" k8-charts/ordersh/values.yaml

      # 1Ô∏è‚É£1Ô∏è‚É£ Commit Helm changes (GitOps handoff to ArgoCD)
      - name: Commit Helm changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8-charts/*/values.yaml
          git commit -m "ci: update image tags to ${{ github.sha }}"
          git push
      # test